# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-25 07:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, height_field=b'height_field', null=True, upload_to=b'upload_location', width_field=b'width_field')),
            ],
        ),
        migrations.CreateModel(
            name='Musings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, height_field=b'height_field', null=True, upload_to=b'upload_location', width_field=b'width_field')),
                ('description', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(blank=True, height_field=b'height_field', null=True, upload_to=b'upload_location', width_field=b'width_field')),
                ('description', models.CharField(max_length=1000)),
                ('link', models.URLField(max_length=500)),
                ('github', models.URLField(max_length=500)),
            ],
        ),
    ]
